name: build
on:
  - pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: sudo apt install -yq automake bison
      - name: Pre-configure
        run: |
         ./bootstrap.sh && \
         ./configure \
         --disable-debug \
         --disable-tests \
         --without-java \
         --without-erlang \
         --without-python \
         --without-py3 \
         --without-php \
         --without-perl \
         --without-ruby \
         --without-swift \
         --without-haskell \
         --without-go \
         --without-rs \
         --without-netstd \
         --without-c_glib \
         --without-nodejs
      - name: Build
        run: make
