name: Build and upload binaries after release

on:
  release:
    types: [created]

jobs:
  publish:
    name: Build and upload for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact-path: compiler/cpp/cmake-build/bin
            asset-name: thrift-${{ github.ref }}-linux-x86_64.tar.gz
            install-deps: sudo apt install -yq automake bison flex cmake
            build-command: make
          - os: macos-latest
            artifact-path: compiler/cpp/cmake-build/bin/Debug
            asset-name: thrift-${{ github.ref }}-darwin-arm64.tar.gz
            install-deps: brew install automake bison flex cmake && echo "PATH=$(brew --prefix bison)/bin:$PATH" >> $GITHUB_ENV
            build-command: cmake --build .
            cmake-parameters: -G "Xcode"

    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: ${{ matrix.install-deps }}
      - name: Build
        run: |
          cd compiler/cpp && \
          mkdir cmake-build && \
          cd cmake-build && \
          cmake ${{ matrix.cmake-parameters }} .. && \
          ${{ matrix.build-command }}
        env:
          CMAKE_OSX_ARCHITECTURES: arm64
          CXXFLAGS: -std=c++11
      - name: Make dist
        run: mkdir dist && tar -czvf dist/${{ matrix.asset-name }} -C ${{ matrix.artifact-path }} thrift
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/${{ matrix.asset-name }}
          tag: ${{ github.ref }}
