name: build
on:
  - pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install automake bison
      - run: ./bootstrap.sh
      - name: Configure
        run: |
         ./configure \
         --host=amd64-linux \
         --disable-debug \
         --disable-tests \
         --without-java \
         --without-erlang \
         --without-python \
         --without-py3 \
         --without-php \
         --without-perl \
         --without-ruby \
         --without-swift \
         --without-haskell
      - run: make