name: build
on:
  - pull_request

jobs:
  build:
    name: Build
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - run: brew install automake bison boost java erlang autoconf libtool pkg-config boost openssl@1.1
      - name: Set env
        run: echo "PATH=$(brew --prefix bison)/bin:$PATH" >> $GITHUB_ENV
      # - run: export LDFLAGS="-L$(brew --prefix bison)/lib" LDFLAGS='-L$(brew --prefix bison)/lib'
      - run: ./bootstrap.sh
      - run: ./configure --host=aarch64-apple-darwin --disable-debug --disable-tests --with-erlang --with-java --with-openssl=$(brew --prefix openssl@1.1) --with-boost=$(brew --prefix boost) --without-perl --without-php --without-php_extension --without-python --without-ruby --without-swift --without-go --without-rs --without-lua
      - run: make