name: build
on:
  - pull_request

jobs:
  build:
    name: Build
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - run: brew install automake bison@2.7
      - run: export LDFLAGS="-L$(brew --prefix bison)/lib"
      - run: ./bootstrap.sh
      - run: ./configure LDFLAGS='-L$(brew --prefix bison)/lib' --host=aarch64-apple-darwin
      - run: make