name: build
on:
  - pull_request

jobs:
  build:
    name: Build
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - run: brew install automake bison
      - name: Set env
        run: echo "PATH=$(brew --prefix bison)/bin:$PATH" >> $GITHUB_ENV
      # - run: export LDFLAGS="-L$(brew --prefix bison)/lib" LDFLAGS='-L$(brew --prefix bison)/lib'
      - run: ./bootstrap.sh
      - run: ./configure --host=aarch64-apple-darwin --without-perl
      - run: make