name: build
on:
  - pull_request

jobs:
  build:
    name: Build
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - run: brew install automake bison
      - run: export PATH="/opt/homebrew/opt/bison/bin:$PATH"
      - run: export LDFLAGS="-L/opt/homebrew/opt/bison/lib"
      - run: ./bootstrap.sh
      - run: ./configure LDFLAGS='-L/opt/homebrew/opt/bison/lib' --host=aarch64-apple-darwin --without-perl
      - run: make