name: build
on:
  - pull_request

jobs:
  build:
    name: Build
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - run: brew install automake bison
      - name: Set env
        run: echo "PATH=$(brew --prefix bison)/bin:$PATH" >> $GITHUB_ENV
      - run: ./bootstrap.sh
      - name: Configure
        run: |
         ./configure \
         --host=aarch64-apple-darwin \
         --disable-debug \
         --disable-tests \
         --without-java \
         --without-erlang \
         --without-python \
         --without-py3 \
         --without-php \
         --without-perl \
         --without-ruby \
         --without-swift
      - run: make