name: build
on:
  - pull_request

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: brew install automake bison flex cmake && echo "PATH=$(brew --prefix bison)/bin:$PATH" >> $GITHUB_ENV
      - name: Build with XCode
        run: |
          cd compiler/cpp && \
          mkdir cmake-build && \
          cd cmake-build && \
          cmake -G "Xcode" .. && \
          cmake --build .
        env:
          CFLAGS: -target arm64-apple-macos11
          CMAKE_OSX_ARCHITECTURES: arm64;x86_64
      - name: Build
        run: make
      - name: Check arch
        run: lipo -archs compiler/cpp//thrift
